version: "3.9"
services:
  redis-prime:  
    image: eqalpha/keydb:latest
    ports: 
      - "41001:6379"
  redis-us-1:  
    image: eqalpha/keydb:latest
    ports: 
      - "41002:6379"
  redis-jp-1:  
    image: eqalpha/keydb:latest
    ports: 
      - "41004:6379"
  postgres-us-1:
    image: postgres
    ports: 
      - "42002:5432"
    environment:
      - POSTGRES_PASSWORD=four
  postgres-jp-1:
    image: postgres
    ports: 
      - "42004:5432"
    environment:
      - POSTGRES_PASSWORD=four